feature: Ability to scan both normal codes and inverted codes
juliansteenbakker/mobile_scanner pull request #1215
Opened 2024-10-12 00:53 UTC by RafaRuiz

Started on #1214 to improve #1071 but with a few enhancements:
- No usage of OpenCV for Android, MLKit would do the inversion.
- Set `intervalInvertImage` instead of choosing whether to invert the image constantly or not. This way we can read both types, for example:
<details>
<summary>Both types of codes (example)</summary>

![image](https://github.com/user-attachments/assets/70c9e3f8-9042-4488-87de-6deda803bfdc)

</details>

- Kept to latest version 6.0.1 instead from the first one which was taken from 5.0.1

2024-10-14 14:43 UTC, navaronbracke requested changes
Overall, this looks okay, but I have feedback for the implementation.

Will you be looking into color inversion for the Vision API (for MacOS) as well?

2024-10-14 14:43 UTC, navaronbracke commented on lib/src/objects/start_options.dart
> +  /// Whether the scanner should work also with inverted images.
This doc comment can be improved.
```suggestion
  /// Whether the scanner should try to detect color-inverted barcodes in every other frame.
```

2024-10-14 14:43 UTC, navaronbracke commented on lib/src/mobile_scanner_platform_interface.dart
> +  Future<void> setIntervalInvertImage(bool intervalInvertImage) {
I don't think a new method on the public interface is needed?

Unless you have a specific use case for it?

2024-10-14 14:43 UTC, navaronbracke commented on lib/src/mobile_scanner_controller.dart
> +  /// Whether the image should be inverted in intervals (original - inverted - original…)
```suggestion
  /// Whether the scanner should try to detect color-inverted barcodes in every other frame.
  ///
  /// When this option is enabled, every odd frame from the camera preview has its colors inverted before processing.
  /// This is useful if barcodes can be both black-on-white (the most common) and white-on-black (less common).
  /// Usage of this parameter can incur a performance cost, as some frames need to be altered further during processing.
  ///
  /// Defaults to false and is only supported on Android and iOS.
```

We should provide users with a detailed description of what this does.

2024-10-14 14:43 UTC, navaronbracke commented on lib/src/mobile_scanner_controller.dart
> +  final bool intervalInvertImage;
I find the name `intervalInvertImage` a bit confusing for the public API.

What about `scanInverted` ? Open to better name suggestions.

2024-10-14 14:43 UTC, navaronbracke commented on android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt
> +        // Inversion
```suggestion
        // Invert every other frame.
```

The comment next to the assignment can be removed. We can just keep the comment at the top.

2024-10-14 14:43 UTC, navaronbracke commented on android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt
> +    private var invertImage: Boolean = false
```suggestion
    private var invertCurrentImage: Boolean = false
```

2024-10-14 14:43 UTC, navaronbracke commented on android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt
> +    // Helper function to invert image data
```suggestion
    private fun invertBytes(bytes: ByteArray): ByteArray {}
```

We can omit the comment if the method says what it does :)

2024-10-14 14:43 UTC, navaronbracke commented on android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt
> +        // Invert the cropped image
The image isn't really cropped? So this comment is misleading.

2024-10-14 14:43 UTC, navaronbracke commented on android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt
> +    private fun yuv420888toNV21(image: Image): ByteArray {
We have an open bug for avoiding the use of `yuv420_888`: https://github.com/juliansteenbakker/mobile_scanner/issues/1116

I'd rather fix that bug first, instead of adding a new dependency on YUV here.
If you don't want to fix that bug, I would suggest we move this conversion from YUV to the
utils folder at https://github.com/juliansteenbakker/mobile_scanner/tree/master/android/src/main/kotlin/dev/steenbakker/mobile_scanner/utils

When we fix that other formats bug, we can just delete all the YUV related utils.

2024-10-14 14:43 UTC, navaronbracke commented on ios/Classes/MobileScannerPlugin.swift
> +    func convertCIImageToCGImage(inputImage: CIImage) -> CGImage? {
This function seems to be unused? It is a copy of the one in MobileScanner.swift

2024-10-14 14:43 UTC, navaronbracke commented on ios/Classes/MobileScanner.swift
> +    func convertCIImageToCGImage(inputImage: CIImage) -> CGImage? {
Can this be private?

2024-10-14 14:43 UTC, navaronbracke commented on ios/Classes/MobileScanner.swift
> +                let tempImage = self.invertImage(image: latestBuffer.image)
This temp variable is redundant

2024-10-14 14:43 UTC, navaronbracke commented on ios/Classes/MobileScanner.swift
> +    /// Analyze inverted image intervally to include both inverted and normal images
```suggestion
var intervalInvertImage: Bool = false
private var invertCurrentImage: Bool = false
```

Same name suggestion as on Android. The comments can also be removed.

2024-10-14 14:43 UTC, navaronbracke commented on ios/Classes/MobileScanner.swift
> +            // Inversion
```suggestion
            // Invert every other frame.
```

2024-10-14 14:43 UTC, navaronbracke commented on ios/Classes/MobileScanner.swift
> +        let visImage = VisionImage(image: uiImage)
```suggestion
        let visionImage = VisionImage(image: uiImage)
```

2024-10-14 14:43 UTC, navaronbracke commented on ios/Classes/MobileScanner.swift
> +        var uiImage = image
```suggestion
let uiImage: UiImage

if (invertImage) {
  uiImage = self.invertImage(image: image)
} else {
  uiImage = image
}
```

Can you also use a `let` here?

2024-10-14 14:43 UTC, navaronbracke commented on ios/Classes/MobileScanner.swift
> +    func invertImage(image: UIImage) -> UIImage {
Can this be private?

2024-10-14 14:43 UTC, navaronbracke commented on ios/Classes/MobileScanner.swift
> +        let filter = CIFilter(name: "CIColorInvert")
I would not use a magic string here, you should be using https://developer.apple.com/documentation/coreimage/cifilter/3228292-colorinvert

2024-10-14 18:25 UTC, RafaRuiz commented on lib/src/mobile_scanner_controller.dart
> +  final bool intervalInvertImage;
`interval` is the word that came to me.
maybe `shouldConsiderInvertedImages: bool`?
`scanInverted` looks like it would work only with inverted colour images

2024-10-14 18:26 UTC, RafaRuiz commented on android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt
> +        // Invert the cropped image
Nope! I cropped it to avoid the bounds and see results fast. I'll fix it 👍

2024-10-16 06:28 UTC, navaronbracke commented on lib/src/mobile_scanner_controller.dart
> +  final bool intervalInvertImage;
That would be sufficient for a name.

2024-10-18 08:50 UTC, RafaRuiz commented on lib/src/mobile_scanner_platform_interface.dart
> +  Future<void> setIntervalInvertImage(bool intervalInvertImage) {
Yes, throughout the comments I've seen that some users generate their own **normal** QR codes and it's at their use, so I thought why allowing inverted images if it's not going to be used for them, it's a waste of energy.

2024-10-18 08:52 UTC, RafaRuiz commented on ios/Classes/MobileScanner.swift
> +    /// Analyze inverted image intervally to include both inverted and normal images
I kept the private temp var's comment and enhanced it. Let me know if that's alright
![image](https://github.com/user-attachments/assets/115afdd3-7dd4-45af-abf0-642684060d07)

2024-10-18 10:01 UTC, RafaRuiz commented on ios/Classes/MobileScanner.swift
> +        let filter = CIFilter(name: "CIColorInvert")
@navaronbracke can you give me a hand here?

I'm trying to make it API available, as I've seen there are a few statements for iOS 13 somewhere in the project, but despite setting my project deployment target to 15, I keep seeing this:

![image](https://github.com/user-attachments/assets/08c77799-0969-4812-aa18-ecefc2ae323e)

I've done just a little Swift in my life, it's been more Android

2025-01-16 08:51 UTC, navaronbracke requested changes
@juliansteenbakker This entire implementation would omit MacOS, even though that should be supported there also, considering the API's we use.

Since this is a draft, can we close this PR and reopen this on the dev branch instead?

2025-01-16 08:51 UTC, navaronbracke commented on lib/src/mobile_scanner_platform_interface.dart
> +  /// Set inverting image colors in intervals (for negative Data Matrices).
```suggestion
  /// Enable or disable the inverting of image colors.
  ///
  /// This is useful when working with negative-color Data Matrices.
  /// See also: https://en.wikipedia.org/wiki/Negative_(photography)
```

2025-01-16 08:51 UTC, navaronbracke commented on lib/src/mobile_scanner_controller.dart
> +  /// Defaults to false.
The second `Defaults to false.` can be removed.

2025-01-16 08:51 UTC, navaronbracke commented on lib/src/method_channel/mobile_scanner_method_channel.dart
> +      {'shouldConsiderInvertedImages': shouldConsiderInvertedImages},
Can we just pass in a boolean flag instead of a Map here?

2025-01-16 08:51 UTC, navaronbracke commented on android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt
> +        // Invert every other frame.
```suggestion
        // Invert every other frame, by flipping the flag on every input frame.
```

2025-01-16 08:51 UTC, navaronbracke commented on android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt
> +            invertCurrentImage = !invertCurrentImage // so we jump from one normal to one inverted and viceversa
```suggestion
            invertCurrentImage = !invertCurrentImage
```

2025-01-16 08:51 UTC, navaronbracke commented on android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt
> +        YuvToRgbConverter(activity).yuvToRgb(image, bitmap)
This adds another usage of the deprecated RenderScript API's. Can we avoid this?

See #1142

2025-01-16 08:51 UTC, navaronbracke commented on ios/Classes/MobileScannerPlugin.swift
> +        if (shouldConsiderInvertedImages == nil) {
Can we guard `mobileScanner.setShouldConsiderInvertedImages(shouldConsiderInvertedImages!)` to not do anything if the argument is null ? Otherwise this does not match Android.

2025-01-16 08:51 UTC, navaronbracke commented on ios/Classes/MobileScanner.swift
> +    // local variable to invert this image only this time,
I think this can be a one line comment.

```suggestion
    // This flag is used to determine if the current frame should be color-inverted.
```

2025-01-16 08:56 UTC, juliansteenbakker commented
Sounds good to me @navaronbracke. The android implementation can be a lot faster, i will work on it. I'll first merge the changes from master into develop, before fixing the merge conflicts on this PR.

2025-01-17 17:19 UTC, juliansteenbakker commented
@navaronbracke do you see any usecase for the `setShouldConsiderInvertedImages` function in the interface? I don't think we would want to set options via functions, it would be best to just let the `MobileScannerController` handle this with `shouldConsiderInvertedImages` parameter.

2025-01-17 17:32 UTC, navaronbracke commented
@juliansteenbakker I agree, you'd probably want to set it up on the controller itself. That follows the same pattern for the other options.

2025-01-19 12:39 UTC, juliansteenbakker commented
I have added some improvements, and i think this is the best form we will get with this implementation. Yes, android.renderscript is deprecated, but with the current implementation it's the best/fastest way of transforming images. I think we still need to migrate to something new, but that would be a new issue/pr to fix this. #1142

2025-01-19 19:01 UTC, navaronbracke requested changes
The change overall is LGTM. I just have some minor feedback.

2025-01-19 19:01 UTC, navaronbracke commented on lib/src/mobile_scanner_controller.dart
> +  /// Whether the scanner should try to detect color-inverted barcodes in every other frame.
Is this wording still correct? As it stands now, Android uses the flag, but never for "every other" frame.
When it is enabled, it currently applies the inversion for every frame.

2025-01-21 13:49 UTC, juliansteenbakker commented on example/lib/barcode_scanner_controller.dart
> -    torchEnabled: true,
After testing many times in the evening i finally got fed up with the flash in my eyes, so it's about time!

2025-01-24 09:23 UTC, merged

2025-02-10 19:34 UTC, navaronbracke commented
@RafaRuiz iOS & MacOS use the Vision API. That API should already support color inverted barcodes IIRC.
See also https://developer.apple.com/documentation/vision/vnbarcodeobservation/iscolorinverted

2025-02-11 05:05 UTC, RafaRuiz commented
> @RafaRuiz iOS & MacOS use the Vision API. That API should already support color inverted barcodes IIRC. See also https://developer.apple.com/documentation/vision/vnbarcodeobservation/iscolorinverted

I don't understand. Apparently the inverted images would be working on Android with this library and not on iOS because there hasn't been any code bridged to it.