Fix start error handling
juliansteenbakker/mobile_scanner pull request #373
Opened 2022-11-20 14:04 UTC by navaronbracke

This PR updates the error handling for the `MobileScanner.start()` function.

It also updates some pieces of the public API and fixes several bugs.

See the updated changelog for an overview.

Fixes: #371

2022-11-20 14:28 UTC, navaronbracke commented on example/lib/main.dart
> -            ElevatedButton(
This one is no longer relevant, since the controller is now required.

2022-11-20 14:29 UTC, navaronbracke commented on lib/mobile_scanner.dart
> +export 'src/enums/mobile_scanner_error_code.dart';
I exported these so that users can handle errors properly. Previously the `MobileScannerException` was not exported.

2022-11-20 14:30 UTC, navaronbracke commented on lib/src/mobile_scanner.dart
> -typedef MobileScannerCallback = void Function(BarcodeCapture barcodes);
I removed these typedefs, since they add no value and the function can be inlined without formatting issues.

2022-11-20 14:33 UTC, navaronbracke commented on lib/src/mobile_scanner.dart
> +                        ? HtmlElementView(viewType: value.webId!)
Isn't using `HtmlElementView` / `Texture` directly unsafe? On the other hand, this plugin is not a federated plugin,
so there is no `MobileScannerPlatformInterface` / `mobile_scanner_android` `mobile_scanner_web` distinction.

Maybe you could do that in the future though. Then the platform interface has a method that creates a `Widget` which is one of the two depending on the platform.

package `video_player` does that too.

2022-11-20 14:34 UTC, navaronbracke commented on lib/src/mobile_scanner.dart
> -  void didUpdateWidget(covariant MobileScanner oldWidget) {
This is no longer needed, since the controller cannot be null, and we use `widget.controller` directly.

2022-11-21 07:59 UTC, juliansteenbakker requested changes
Thank you for your contribution! I think a lot of changes are good, but i still have a few concerns about the controller being required.

2022-11-21 07:59 UTC, juliansteenbakker commented on lib/src/mobile_scanner.dart
> +                        ? HtmlElementView(viewType: value.webId!)
That would be a better approach, but for now i think it's working without problems.

2022-11-21 07:59 UTC, juliansteenbakker commented on lib/src/mobile_scanner.dart
> +    required this.controller,
I know that requiring a controller fixes some problems in the codebase, however i don't know if this is the right approach. For example, all Flutter widgets that have controller structure such as [PageView](https://api.flutter.dev/flutter/widgets/PageView-class.html) don't require a controller. So i would still rather want the controller to be optional. I understand that we would need a different error approach, but maybe we could rather implement a callback function which sends the error code back to the user instead of throwing an exception. What do you think about this?

2022-11-21 07:59 UTC, juliansteenbakker commented on lib/src/mobile_scanner.dart
> +  final void Function(BarcodeCapture barcodes) onBarcodeDetected;
I think it's best to let it be `onDetect` since it are not necessarily barcodes but also QR codes and such which can be detected. I think it's better to change the class name of `BarcodeCapture` to something more generic than to rename this callback function.

2022-11-21 09:15 UTC, navaronbracke commented on lib/src/mobile_scanner.dart
> +    required this.controller,
I understand that you'd want the controller to be optional. I'll revert that change.

In terms of handling errors, I think that having to only use a `try/catch / catchError()` is a better public API
and it fits with the natural way of working with futures. Also callbacks _can_ get messy, so I'd rather avoid them.

2022-11-21 09:16 UTC, navaronbracke commented on lib/src/mobile_scanner.dart
> +  final void Function(BarcodeCapture barcodes) onBarcodeDetected;
Good point, I'll revert this change.

2022-11-21 11:11 UTC, navaronbracke commented on lib/src/mobile_scanner.dart
> +  final void Function(BarcodeCapture barcodes) onBarcodeDetected;
Done

2022-11-21 11:12 UTC, navaronbracke commented on lib/src/mobile_scanner.dart
> +    required this.controller,
@juliansteenbakker I reverted the required controller, but I kept the error handling as is.

2022-11-21 11:16 UTC, navaronbracke commented on lib/src/mobile_scanner.dart
> +        _controller = MobileScannerController();
@juliansteenbakker this controller is never started, is that intended?

2022-11-21 11:31 UTC, navaronbracke commented
@juliansteenbakker apparently, there is a bug in the example app where a controller is provided. I think it needs to rebuild when the permission is granted. (it also does not show anything when it is rejected) I'll get to fixing that.

Also, I see that when calling stop and the controller is already stopped, the platform code throws. Should we just ignore that case instead of throwing?

Lastly, I see that the example app uses a logging service, thats only in the example app, right?

2022-11-22 09:25 UTC, navaronbracke commented
@juliansteenbakker I'm going to split off the fixes unrelated to the error handling / permission bug into a separate PR, so that we can get those merged first.

After that I'll rebase this branch and hopefully we can fix the issue with permissions then.

2022-11-22 09:48 UTC, juliansteenbakker commented
>  I'm going to split off the fixes unrelated to the error handling / permission bug into a separate PR, so that we can get those merged first.

Sounds good to me!

2022-11-22 11:16 UTC, navaronbracke commented
I put those fixes in here https://github.com/juliansteenbakker/mobile_scanner/pull/375

2022-11-25 10:37 UTC, juliansteenbakker commented
Thanks for creating all these PR's. I don't have time this week anymore to check these, but i will check these first thing next week.

2022-12-08 10:17 UTC, merged

2023-03-27 07:45 UTC, saibotma commented on lib/src/mobile_scanner.dart
> +          child: LayoutBuilder(
Is the `LayoutBuilder` actually required? Why is using `MediaQuery` not sufficient anymore? I am asking because `LayoutBuilder` can't be used inside an `IntrinsicHeight` widget.

2023-03-27 07:51 UTC, navaronbracke commented on lib/src/mobile_scanner.dart
> +          child: LayoutBuilder(
You could use 

```
final Size size = MediaQuery.sizeOf(context);

final double screenWidth = size.width;
```
instead if you want.

The sole purpose of `LayoutBuilder` was to avoid using MediaQuery to get just the screen size.

Doing a regular `MediaQuery.of(context)` makes the widget rebuild if anything in `MediaQueryData` changes, i.e. `textScaleFactor`. Using the more specified methods on MediaQuery allows to use the correct aspect of the InheritedModel, therefor filtering rebuilds more efficiently.

See https://api.flutter.dev/flutter/widgets/InheritedModel-class.html

2023-03-29 21:14 UTC, saibotma commented on lib/src/mobile_scanner.dart
> +          child: LayoutBuilder(
Using `MediaQuery.sizeOf` sounds promising. Nevertheless, I actually don't understand why having it like this is not sufficient. Why is it actually necessary to wrap it in two `SizedBox`es and a `FittedBox`?

return ClipRect(
    child: kIsWeb
        ? HtmlElementView(viewType: value.webId!)
        : Texture(textureId: value.textureId!),
);