feature/increase-camera-quality
juliansteenbakker/mobile_scanner pull request #760
Opened 2023-09-26 10:02 UTC by EArminjon

2023-10-02 08:47 UTC, mocmeow commented
I've tested your fix and it do really improve the scan distance and speed, difference is noticeably specially on not a really good cam like 5 or 8mpx cam and 16 digits barcode. No problem has been found so far, I'm waiting for a merge soon. 
Great job, thank you!

2023-10-11 17:07 UTC, bswhite1 approved these changes

2023-10-12 11:06 UTC, EArminjon commented
Hello @juliansteenbakker

What do you think of this PR ?

2023-10-12 14:35 UTC, juliansteenbakker commented on android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt
> +        val heightMaxRes = 640 * 4;
Thanks for the update and sorry for the delay. I have just one question: The resolution is now set to 2560 * 1920. Wouldn't it be better to make this user configurable, so in case there is an issue on some device, the resolution can be scaled down. I can imagine some older devices having trouble with this high resolution.

2023-10-12 15:25 UTC, navaronbracke commented on android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt
> +        val heightMaxRes = 640 * 4;
I agree with this point. The `camera` package does something similar.

2023-10-12 15:55 UTC, EArminjon commented on android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt
> +        val heightMaxRes = 640 * 4;
Okay, i can let user provide two parameters : maxResolutionHeight and maxResolutionWidth.
Where must i add that ? Inside MobileScannerController properties or inside the MobileScanner properties ?
As it is only used by Android, must i put that inside an AndroidSettings models ?

2023-10-12 15:56 UTC, EArminjon commented on android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt
> +        val heightMaxRes = 640 * 4;
Also note that, Android said if the resolution is not available, Android will take the closest one.

2023-10-12 16:29 UTC, navaronbracke commented on android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt
> +        val heightMaxRes = 640 * 4;
@EArminjon The configuration should be passed to the Dart-side and the native side. So you'll have to do some plumbing here and there.

If this is only for Android, then documenting that limitation is good enough.

I would go with a https://api.flutter.dev/flutter/dart-ui/Size-class.html as the type of this parameter (so that we do not have 2 values to pass around)

You can use the newer ResolutionSelector API to make it work on newer version of Android.

2023-10-12 16:37 UTC, EArminjon commented on android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt
> +        val heightMaxRes = 640 * 4;
Yep i will provide a size, more efficient.
I tried to use the new api but I didn't achieve to make something working. Android native is not really easy for me...

2023-10-13 07:23 UTC, EArminjon commented
Usage : 

```dart
MobileScannerController(
    androidResolution: const Size(1920, 2560),
)
```

2023-10-13 09:33 UTC, navaronbracke requested changes
Some minor remarks, but otherwise this looks good.

2023-10-13 09:33 UTC, navaronbracke commented on lib/src/mobile_scanner_controller.dart
> +  /// Can be used to override default Android camera resolution.
Could you rename this property to just `cameraResolution` ? Maybe one day, we can use this to configure resolutions on other platforms as well.

```suggestion
/// The desired resolution for the camera.
///
/// When this value is provided, the camera will try to match this resolution,
/// or fallback to the closest resolution available.
/// When this is null, Android defaults to a resolution of 640x480.
///
/// Bear in mind that changing the resolution has an effect on the aspect ratio.
///
/// When the camera orientation changes,
/// the resolution will be flipped to match the new dimensions of the display.
///
/// Currently only supported on Android.
final Size? cameraResolution;
```

2023-10-13 09:33 UTC, navaronbracke commented on android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt
> +    // If we return an higher resolution than device can handle, camera package take the most relevant one available.
What do you mean with 

```
If we return an higher resolution than device can handle, camera package take the most relevant one available.
```

Is the CameraX library handling it for us already? (Not a CameraX expert myself)

2023-10-13 09:33 UTC, navaronbracke commented on android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt
> +                displayManager.registerDisplayListener(object : DisplayManager.DisplayListener {
I have a feeling that this display listener does several things wrong for now.

1. We recreate it every time
2. We never unset the listener when we no longer need it

Could you look into this? If you can't find a solution right away, could you add a TODO in the code and create a Github issue? Then we can follow up with this later.

My first guess would be to set up a display listener as a property of the MobileScanner,
keep track of the analysisBuilder (if possible) and do some delegation with that.

2023-10-13 09:42 UTC, EArminjon commented on android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt
> +    // If we return an higher resolution than device can handle, camera package take the most relevant one available.
Android camera library will adapt the requested resolution if not possible : 
![image](https://github.com/juliansteenbakker/mobile_scanner/assets/37028599/4495d730-d4a7-46e5-af23-8231801f3761)

2023-10-13 09:48 UTC, EArminjon commented
> @EArminjon did you manage to use the newer API, which replaces the deprecated setTargetResolution on newer Android versions? That is going to be a requirement for this as well.
That also mean current camera2 package to camera2 version 1.3. 

I'm not native expert, could take responsability of this :/

2023-10-13 09:51 UTC, navaronbracke commented
I can take a look for that for you.

2023-10-13 12:18 UTC, navaronbracke commented
@EArminjon I found a solution for the display listener (and the deprecated window display getter)

2023-10-13 12:34 UTC, EArminjon commented
@navaronbracke  PR updated : 
- variable renamed from androidResolution to cameraResolution.
- listener is now disposed (ty for pointing this)

2023-10-13 12:46 UTC, navaronbracke commented
@EArminjon Apparently we did things side-by-side :)

I fixed the display listener issue in a slightly different way in https://github.com/juliansteenbakker/mobile_scanner/pull/785
so that we don't need to keep track of the window manager as well.

I also fixed a small warning about a private method in the Android code and fixed a deprecated API usage.

Your original commits are included in that PR as well (except for the things we did in parallel)

2023-10-13 12:49 UTC, EArminjon commented
> @EArminjon Apparently we did things side-by-side :)
> 
> I fixed the display listener issue in a slightly different way in #785 so that we don't need to keep track of the window manager as well.
> 
> I also fixed a small warning about a private method in the Android code and fixed a deprecated API usage.
> 
> Your original commits are included in that PR as well (except for the things we did in parallel)

I'm happy to see that my fix was closest to yours, i'm pretty junior in Android Native. 
Ty for making this better ressource cleanup <3 !

I close this PR right ?

2023-10-13 12:49 UTC, closed without merging

2023-10-13 12:52 UTC, navaronbracke commented
Yes that is correct. While looking at your latest commit I also found an error I made, we can indeed use `DisplayManager.DisplayListener` with an anonymous object (instead of using a separate class)

I added that to the other PR as well. Thank you!