Scanner with overlay screen added
juliansteenbakker/mobile_scanner pull request #798
Opened 2023-10-18 16:49 UTC by Spyy004

Here are the things that I have done
1) Added an overlay text which would show Please scan QR code when no QR code is scanned
2) Added a scanwindow and added white border radius to it. 
3) Added two extra buttons namely flashlight and toggleCamera view.
4) Modified the functionality of FAB. The FAB is now invisible once the camera state opens.

Please review the PR and tell me if you need any changes to it or any new additions to it.

2023-10-18 20:52 UTC, navaronbracke commented
I will try to review it in the coming days.

2023-10-20 17:43 UTC, navaronbracke requested changes
I have some small remarks, but you did good already!

2023-10-20 17:43 UTC, navaronbracke commented on example/lib/mobile_scanner_overlay.dart
> -//TODO: Create example with scanner overlay
Could you remove the commented out code here? Since we now have a sample, this old code is not needed anymore.

2023-10-20 17:43 UTC, navaronbracke commented on example/lib/mobile_scanner_overlay.dart
> +void main() {
Why is there a separate `void main() {}` entrypoint here? The example app already includes an entrypoint in `example/lib/main.dart`.

The widget `BarcodeScannerWithOverlay` should be the only one in this file, as the example app already includes a route to display that widget. So you can remove the `void main() {}` and `HomePage` widget in this file.

2023-10-20 17:43 UTC, navaronbracke commented on example/lib/mobile_scanner_overlay.dart
> +  _MyAppState createState() => _MyAppState();
Could you rename the state class to include the name of the widget? This is a common pattern when creating StatefulWidgets.

```suggestion
class BarcodeScannerWithOverlay extends StatefulWidget {
  @override
   _BarcodeScannerWithOverlayState createState() => _BarcodeScannerWithOverlayState();
}

class _BarcodeScannerWithOverlayState extends State<BarcodeScannerWithOverlay> {
  // ...
}
```

2023-10-20 17:43 UTC, navaronbracke commented on example/lib/mobile_scanner_overlay.dart
> +  late BarcodeCapture currentBarcodeCapture ;
Prefer using a nullable value over a late one. If a late variable is not initialized, you get a `LateInitializationError`, which is harder to detect.

There is also an extra space here.

```suggestion
 BarcodeCapture? currentBarcodeCapture;
```

2023-10-20 17:43 UTC, navaronbracke commented on example/lib/mobile_scanner_overlay.dart
> +  @override
This `initState()` method does nothing? It can be removed.

2023-10-20 17:43 UTC, navaronbracke commented on example/lib/mobile_scanner_overlay.dart
> +  String? qr;
You can get the QR code from the BarcodeCapture value, so the `qr` property is not needed?

2023-10-20 17:43 UTC, navaronbracke commented on example/lib/mobile_scanner_overlay.dart
> +  bool camState = false;
```suggestion
  bool cameraStarted = false;
```

2023-10-20 17:43 UTC, navaronbracke commented on example/lib/mobile_scanner_overlay.dart
> +    facing: CameraFacing.back,
Since you mention having to scan a QR code, specifying the formats is a good thing to do.

```suggestion
    facing: CameraFacing.back,
    formats: const [BarcodeFormat.qrCode],
    autoStart: false,
```

2023-10-20 17:43 UTC, navaronbracke commented on example/lib/mobile_scanner_overlay.dart
> +    super.dispose();
For lifecycle methods, if it is a positive method (create, resume etc), the `super` goes first.
If it is a negative method (dispose, stop etc), the `super` goes last.

```suggestion
  @override
  dispose() {
    controller.dispose();
    super.dispose();
  }
```

2023-10-20 17:43 UTC, navaronbracke commented on example/lib/mobile_scanner_overlay.dart
> +  configureCameraSettings() {
```suggestion
  startCamera() {
```

2023-10-20 17:43 UTC, navaronbracke commented on example/lib/mobile_scanner_overlay.dart
> +  onBarcodeDetect(BarcodeCapture barcodeCapture) {
Could you fix the indentation for this method, by using `dart format` ?

2023-10-20 17:43 UTC, navaronbracke commented on example/lib/mobile_scanner_overlay.dart
> +
There are 2 empty lines here that can be removed.

2023-10-20 17:43 UTC, navaronbracke commented on example/lib/mobile_scanner_overlay.dart
> +    final height = MediaQuery.of(context).size.height;
Could you do this instead?

`final Size size = MediaQuery.sizeOf(context);`

If `MediaQuery.sizeOf` is not found, you should probably increase the minimum Flutter version of the example in `example/pubspec.yaml`

2023-10-20 17:43 UTC, navaronbracke commented on example/lib/mobile_scanner_overlay.dart
> +                          onDetect: (BarcodeCapture barcodeCapture) => {
Could you pass the function directly?

```suggestion
onDetect: onBarcodeDetect,
```

2023-10-20 17:43 UTC, navaronbracke commented on example/lib/mobile_scanner_overlay.dart
> +                        Positioned(
Could you use an `Align` with some padding for the child instead of a Positioned? Then we do not have "magic numbers" for the left and bottom. You can use `Alignment.bottomCenter` for positioning the child.

2023-10-20 17:43 UTC, navaronbracke commented on example/lib/mobile_scanner_overlay.dart
> +                              IconButton(onPressed: ()=>{
```suggestion
onPressed: () => controller.toggleTorch(),
```

2023-10-20 17:43 UTC, navaronbracke commented on example/lib/mobile_scanner_overlay.dart
> +                              IconButton(onPressed: ()=>{
```suggestion
onPressed: () => controller.switchCamera(),
```

2023-10-20 17:43 UTC, navaronbracke commented on example/lib/mobile_scanner_overlay.dart
> +                      Positioned(
Could you use an `Align` with some padding for the child instead of a Positioned? Then we do not have "magic numbers" for the bottom. You can use Alignment.bottomCenter for positioning the child.

2023-10-20 17:43 UTC, navaronbracke commented on example/lib/mobile_scanner_overlay.dart
> +                        child:Opacity(opacity: 0.7, child:
There are some formatting issues here. Could you apply `dart format` to this file. You might need to add comma's where they are missing.

2023-10-21 04:58 UTC, Spyy004 commented on example/lib/mobile_scanner_overlay.dart
> +    final height = MediaQuery.of(context).size.height;
Can you please explain what would be the issue if we use height directly ?

2023-10-21 04:59 UTC, Spyy004 commented on example/lib/mobile_scanner_overlay.dart
> +                        Positioned(
Any specific number you have in mind for the padding ?

2023-10-21 05:06 UTC, Spyy004 commented
Thanks for the detailed review and feedback. I have updated the PR. Please have a look

2023-10-21 08:03 UTC, navaronbracke commented on example/lib/mobile_scanner_overlay.dart
> +    final height = MediaQuery.of(context).size.height;
Doing `MediaQuery.of(context).size` makes the widget rebuild when any property of the MediaQuery changes.

So it rebuilds when the size changes, but _also_ when for example the `boldTextOverride` changes.

If we do `MediaQuery.sizeOf(context);` then we rebuild only when the size changes.
This method uses the size as an "aspect".

See https://api.flutter.dev/flutter/widgets/InheritedModel-class.html

2023-10-21 08:43 UTC, navaronbracke requested changes
I ran the sample on my phone and it looks amazing already.

Just some small remarks for the updated sample.

2023-10-21 08:43 UTC, navaronbracke commented on example/lib/mobile_scanner_overlay.dart
> +  void onBarcodeDetect(BarcodeCapture barcodeCapture) {
The display value can be null. We can use the raw value as fallback.
In the case where that is also null, just use a message like this?

```suggestion
  void onBarcodeDetect(BarcodeCapture barcodeCapture) {
    final barcode = barcodeCapture.barcodes.last;
  
    setState(() {
      overlayText = barcode.displayValue ?? barcode.rawValue ?? 'Barcode has no displayable value';
    });
  }
```

2023-10-21 08:43 UTC, navaronbracke commented on example/lib/mobile_scanner_overlay.dart
> +  BarcodeCapture? currentBarcodeCapture;
Apologies, it seems that `currentBarcodeCapture` is unused now, since we use the detected barcode
to set the overlay text directly.

Can you remove this unused value?

2023-10-21 08:43 UTC, navaronbracke commented on example/lib/mobile_scanner_overlay.dart
> +                      child: Text("Tap on Camera to activate QR Scanner")),
There is a missing comma here, after the Text widget.

```suggestion
                      child: Text("Tap on Camera to activate QR Scanner"),),
```

2023-10-21 08:43 UTC, navaronbracke commented on example/lib/mobile_scanner_overlay.dart
> +    canvas.drawPath(backgroundWithCutout, backgroundPaint);
It seems that only the border rectangle has rounded corners. Can you have the cutout also provide rounded corners? Otherwise there is a small issue with the corners not having the same border radius.

2023-10-21 08:43 UTC, navaronbracke commented on example/lib/mobile_scanner_overlay.dart
> +                                IconButton(
The `torchEnabled` flag is only to turn on the torch when the scanner starts.

Can you instead use a ValueListenableBuilder and pass the torchState of the controller?
Then it updates when the torch is on or off.

2023-10-21 08:43 UTC, navaronbracke commented on example/lib/mobile_scanner_overlay.dart
> +class BarcodeScannerWithOverlay extends StatefulWidget {
If I start the example and deny the camera permission, I get an unhandled exception and the screen stays white.

Either add a TODO comment to fix this later, or handle the error codes that come from the `start` method.

2023-10-21 10:25 UTC, Spyy004 commented on example/lib/mobile_scanner_overlay.dart
> +class BarcodeScannerWithOverlay extends StatefulWidget {
So I was thinking of adding a try catch block in startCamera() and handling the exception by showing a snackbar. I guess that would work

2023-10-21 10:30 UTC, navaronbracke commented on example/lib/mobile_scanner_overlay.dart
> +class BarcodeScannerWithOverlay extends StatefulWidget {
Yes, that could work as well. If I recall correctly the official `camera` example does that too.

2023-10-21 10:43 UTC, Spyy004 commented
I have updated the PR and made the changes as you requested. Please have a look on the handling camera exception part. I think what I wrote should work. Once again, thanks for the feedback

2023-10-21 11:45 UTC, navaronbracke requested changes
One last remark about the value notifier.

2023-10-21 11:45 UTC, navaronbracke commented on example/lib/mobile_scanner_overlay.dart
> +  final ValueNotifier<bool> torchStateNotifier = ValueNotifier<bool>(false);
There is no need for a separate ValueNotifier, as the controller already has one for the torch state (and updates it when the value changes).

Could you pass `controller.torchState` to the widget below?
Its value is an enum rather than a boolean, but it contains values of off and on states.

2023-10-21 12:41 UTC, navaronbracke approved these changes
Since the ValueNotifier issue is not something that breaks the sample, I'll adjust that later.

Then this sample can be included in the next release.

2023-10-21 12:42 UTC, merged

2023-10-21 13:14 UTC, Spyy004 commented
Oh you merged it. I was going to fix this thing now. Sorry and thanks!
Great experience learning new things!

2023-10-21 15:02 UTC, navaronbracke commented
No problem! I am currently looking into getting the next release published. That's why I had a look at it myself :)