Added screenshots to pubspec.yaml
juliansteenbakker/mobile_scanner pull request #927
Opened 2024-01-12 22:02 UTC by Mastermind-sap

Worked on issue #804 .
Added screenshots of example to pubspec.yaml for publishing to pub.dev

2024-01-15 08:27 UTC, navaronbracke requested changes
Just some remarks around the context of the images.

2024-01-15 08:27 UTC, navaronbracke commented on example/screenshots/controller.png
The blue background looks like something from OBS? (I recognise the icon at least).

Could you replace that with just the regular background that the example app gives?
With the screenshots we want to show to the users how using `mobile_scanner` works, with the example app being the thing they should "see".

2024-01-15 08:27 UTC, navaronbracke commented on example/screenshots/overlay.png
This one is a bit unfortunate. Ideally, we want a screenshot of the overlay here, since that's the point of this part of the sample. Could you update the image?

2024-01-15 08:27 UTC, navaronbracke commented on example/screenshots/listController.png
I don't think this one is needed? The `ValueListenableBuilder` is a different way to use the scanner, but the visual end result will look the same as if you were not using a ValueListenableBuilder?

2024-01-15 08:27 UTC, navaronbracke commented on example/screenshots/withoutController.png
You don't have to add one for this case. The "without controller" case will go away soon, as it has some issues with Widget reparenting in the Widget tree.

2024-01-15 08:27 UTC, navaronbracke commented on example/screenshots/zoomSlider.png
Could you get a slightly different screenshot that does the following:

1) Add a label to the zoom slider, so that people see it modifies the zoom level (i.e. min / max) You can update the example app in this PR to add these labels
 2) Perhaps the camera view can be a zoomed in image ?

2024-01-15 08:29 UTC, navaronbracke commented
@Mastermind-sap One more point: Could you update the issue description to say `Fixes #804` ? Then Github closes the issue when this PR is merged.

2024-01-15 14:08 UTC, navaronbracke commented on example/screenshots/controller.png
Yes that is fine

2024-01-15 14:08 UTC, Mastermind-sap commented on example/screenshots/overlay.png
Gave a black background as the normal background of app was camouflaging the overlay.

2024-01-15 14:08 UTC, Mastermind-sap commented on example/screenshots/listController.png
ok. removed.

2024-01-15 14:08 UTC, Mastermind-sap commented on example/screenshots/withoutController.png
removed

2024-01-15 14:11 UTC, Mastermind-sap commented on example/screenshots/zoomSlider.png
Gave a label and also minimum and maximum zoom percentages. 
As for the screenshot added a QR for the repo itself showing 40% zoom.
But I don't think the zoom functionality is working. It is not working for me.

2024-01-15 14:22 UTC, navaronbracke reviewed
I'm not entirely sure if all the sample images are required.

At least we need one for the normal use, the zoom slider, and the overlay / scan window combination.

Are you able to replace the back / white background with an actual view of the world?
Perhaps we could use the fake view finder of an Android emulator as background?
(The one with the checkerboard in a living room)

2024-01-15 14:22 UTC, navaronbracke commented on example/screenshots/scanWindow.png
Now that I think of it, the `scan window` is only a configuration option. The `overlay` sample is the visual version of that, so this image can be removed.

2024-01-15 14:22 UTC, navaronbracke commented on example/screenshots/pageView.png
Could we perhaps have the example show the active scanner in the middle, but the page before and after slightly visible (but deactivated) as well? Then people can see that this is an actual PageView.

You can tweak the viewport fraction for that. Or we could just delete this image, if you think it doesn't add any value besides the other samples?

2024-01-15 14:35 UTC, navaronbracke commented on example/screenshots/zoomSlider.png
If the zoom is not working for you, could you file an issue? I'll take a look at it.

2024-01-15 20:56 UTC, Mastermind-sap commented on example/screenshots/scanWindow.png
ok removed

2024-01-15 21:05 UTC, Mastermind-sap commented on example/screenshots/pageView.png
I couldn't understand what you want. Actually what is the difference in the page view option is unclear to me.

2024-01-15 21:10 UTC, Mastermind-sap commented
> I'm not entirely sure if all the sample images are required.
> 
> At least we need one for the normal use, the zoom slider, and the overlay / scan window combination.
> 
> Are you able to replace the back / white background with an actual view of the world? Perhaps we could use the fake view finder of an Android emulator as background? (The one with the checkerboard in a living room)

Actually the app is not building in my emulator or device. I was running it in browser only. I can do this using OBS but it would be better if I could just build it on my emulator. Opened an issue regarding the error I am facing #930 . Still if you want i can use OBS to just capture the emulator background and take the screenshot.

2024-01-15 21:26 UTC, navaronbracke commented
> > I'm not entirely sure if all the sample images are required.
> > At least we need one for the normal use, the zoom slider, and the overlay / scan window combination.
> > Are you able to replace the back / white background with an actual view of the world? Perhaps we could use the fake view finder of an Android emulator as background? (The one with the checkerboard in a living room)
> 
> Actually the app is not building in my emulator or device. I was running it in browser only. I can do this using OBS but it would be better if I could just build it on my emulator. Opened an issue regarding the error I am facing #930 . Still if you want i can use OBS to just capture the emulator background and take the screenshot.

Do you have information on why it does not build in the emulator for you?
In regards to the emulator, you can use the take screenshot functionality of the emulator toolbar.

2024-01-15 21:38 UTC, Mastermind-sap commented on example/screenshots/pageView.png
![2024-01-1602-56-47-ezgif com-video-to-gif-converter](https://github.com/juliansteenbakker/mobile_scanner/assets/66560136/0105fc8f-57ad-41d6-bd88-96b42e60790d)

I dont know if gif is supported in pub.dev. But I think a gif would demonstrate the pageview in a nice way something like the above.

2024-01-15 21:42 UTC, Mastermind-sap commented
> > > I'm not entirely sure if all the sample images are required.
> > > At least we need one for the normal use, the zoom slider, and the overlay / scan window combination.
> > > Are you able to replace the back / white background with an actual view of the world? Perhaps we could use the fake view finder of an Android emulator as background? (The one with the checkerboard in a living room)
> > 
> > 
> > Actually the app is not building in my emulator or device. I was running it in browser only. I can do this using OBS but it would be better if I could just build it on my emulator. Opened an issue regarding the error I am facing #930 . Still if you want i can use OBS to just capture the emulator background and take the screenshot.
> 
> Do you have information on why it does not build in the emulator for you? In regards to the emulator, you can use the take screenshot functionality of the emulator toolbar.

I get this error:
```An exception occurred applying plugin request [id: 'com.android.application']
> Failed to apply plugin 'com.android.internal.application'.
   > Android Gradle plugin requires Java 17 to run. You are currently using Java 11.
      Your current JDK is located in C:\Program Files\Android\Android Studio\jbr
      You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.```

I tried installing the latest java SDK and java also. Dont know what keeps triggering this error.

2024-01-15 21:45 UTC, navaronbracke commented on example/screenshots/pageView.png
Well, let me reword it a bit: The image is static (unless it is a gif), so besides the title at the top, the PageView sample _looks_ exactly like the basic controller sample.

If we could use a gif, then the user can see that it is actually a PageView, and not just a single page.

2024-01-15 21:49 UTC, Mastermind-sap commented on example/screenshots/pageView.png
yeah agreed! and i think gifs work in pub.dev as seen [here](https://pub.dev/packages/flutter_gif)

2024-01-15 21:49 UTC, navaronbracke commented
I see. What version of Android Studio do you have? If you are using the Java installation that is bundled with Android Studio, then upgrading Android Studio will help.

See https://developer.android.com/build/jdks which also shows your exact error.

2024-01-15 21:50 UTC, Mastermind-sap commented on example/screenshots/pageView.png
So should i replace the image with the above gif or you have any other changes in mind?

2024-01-15 21:52 UTC, navaronbracke commented on example/screenshots/pageView.png
Yeah, the gif is fine. We can always add different images in the future if features are added.

2024-01-15 22:10 UTC, Mastermind-sap commented
> I see. What version of Android Studio do you have? If you are using the Java installation that is bundled with Android Studio, then upgrading Android Studio will help.
> 
> See https://developer.android.com/build/jdks which also shows your exact error.

Was using Electric Eel version. Worked when I upgraded to Hedgehog version. Thanks.

2024-01-15 22:35 UTC, Mastermind-sap commented
Made all the necessary changes. Please check @navaronbracke 
Also changed the gif to a better one.

2024-01-16 07:08 UTC, navaronbracke commented on example/screenshots/pageView.png
Ah, yes the "called start when already started" issue is a known bug. I have fixed that in my platform interface rework, but we still need to release that version.

You can ignore this error for your PR here.

2024-01-16 07:16 UTC, navaronbracke commented
The new images from the emulator look great!

Two remaining points, though:
- is the green border from the emulator recording? If you press the take screenshot button in the emulator control panel, this should not produce such a green border? Or am I mistaken?
- You can remove the old `controller.png`, `homepage.png` and `zoomSlider.png`, because the new ones are better

2024-01-16 07:50 UTC, Mastermind-sap commented on example/screenshots/pageView.png
ok cool

2024-01-16 07:52 UTC, Mastermind-sap commented on example/screenshots/zoomSlider.png
ok opened #932

2024-01-16 08:18 UTC, Mastermind-sap commented
@navaronbracke I have removed the green border and previous images.
As for the flutter analyze in my system it is showing no issues. Can you tell what is the error? The file locations are correct only I suppose?

2024-01-16 08:26 UTC, navaronbracke commented
If you go to the bottom of this PR and click on the `Details` button of the failed Github Action "flutter / analysis (pull_request)"
it shows the following error:

```
Run flutter analyze
Analyzing mobile_scanner...                                     

warning • The path '.\example\screenshots\homepage.png' doesn't exist • pubspec.yaml:8:[9](https://github.com/juliansteenbakker/mobile_scanner/actions/runs/7538727052/job/20520137002?pr=927#step:7:10) • path_does_not_exist
warning • The path '.\example\screenshots\controller.png' doesn't exist • pubspec.yaml:[10](https://github.com/juliansteenbakker/mobile_scanner/actions/runs/7538727052/job/20520137002?pr=927#step:7:11):9 • path_does_not_exist
warning • The path '.\example\screenshots\returningImage.png' doesn't exist • pubspec.yaml:[12](https://github.com/juliansteenbakker/mobile_scanner/actions/runs/7538727052/job/20520137002?pr=927#step:7:13):9 • path_does_not_exist
warning • The path '.\example\screenshots\zoomSlider.png' doesn't exist • pubspec.yaml:[14](https://github.com/juliansteenbakker/mobile_scanner/actions/runs/7538727052/job/20520137002?pr=927#step:7:15):9 • path_does_not_exist
warning • The path '.\example\screenshots\pageView.gif' doesn't exist • pubspec.yaml:[16](https://github.com/juliansteenbakker/mobile_scanner/actions/runs/7538727052/job/20520137002?pr=927#step:7:17):9 • path_does_not_exist
warning • The path '.\example\screenshots\overlay.png' doesn't exist • pubspec.yaml:[18](https://github.com/juliansteenbakker/mobile_scanner/actions/runs/7538727052/job/20520137002?pr=927#step:7:19):9 • path_does_not_exist

6 issues found. (ran in 9.3s)
Error: Process completed with exit code 1.
```

Is `flutter analyze .` working locally without issues?

2024-01-16 09:59 UTC, Mastermind-sap commented
Locally its working for me whether i give ```.\```  or don't. I gave ```.\```  as the workflow was failing but it is still failing.
Local system output:
```dir\mobile_scanner> flutter analyze
Analyzing mobile_scanner...                                             
No issues found! (ran in 18.9s)
```
Let me just change the forward slash to backward slash according to the medium article.(maybe it is due to difference between file paths format in linux and windows)

2024-01-16 10:10 UTC, navaronbracke commented
Seems like it was :) 
I'll file an issue for the Pub client, the error message can be better in this case.

2024-01-16 10:11 UTC, navaronbracke approved these changes

2024-01-16 10:11 UTC, navaronbracke commented
cc @juliansteenbakker for secondary review

2024-01-29 08:43 UTC, juliansteenbakker commented
Looks good!

2024-01-29 08:43 UTC, juliansteenbakker approved these changes

2024-01-29 08:43 UTC, merged